### ISSUE TITLE
How to take screenshot of entire screen like PrtSc

### ISSUE THREAD

**Issue by Jagadeesh09-dev** [Anup2712/Sharescreenshot#1]

**Comment by Anup2712** [comment]
Screenshot(
      controller: screenshotController,
      child: Scaffold(
        appBar: ....
        body: Container(
          ......// refer repository
        ),
        floatingActionButton: FloatingActionButton(
          onPressed: () async {
            _takeScreenshotandShare();
          },
          tooltip: 'Increment',
          child: Icon(Icons.share),
        ),
      ),
    )

refer this repository. i have done this what you want

**Comment by Jagadeesh09-dev** [comment]
It is helping me only to capture the flutter application screen/widget even I am using any other application. But I want to track all activities on the machine while flutter application is running in background. for example when flutter app is running in background and chrome is active on screen, it should capture present visible screen of the machine.
